[package]
name = "shared"
version = "0.1.0"
authors = ["Thomas Gouveia <thomas.gouveia@ioterop.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.50"