[package]
<<<<<<< HEAD:riklet/src/crates/daemon/Cargo.toml
name = "daemon"
=======
name = "oci"
>>>>>>> origin/runner-implementation:riklet/src/crates/oci/Cargo.toml
version = "0.1.0"
authors = ["Hugo Amalric <hugoamalric@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD:riklet/src/crates/daemon/Cargo.toml

# client binary
[[bin]]
name = "client"
path = "riklet.rs"
=======
shared = { path = "../shared" }
log = "0.4.14"
snafu = "0.6.10"
tokio = { version = "1.7.0", features = ["full"] }
async-trait = "0.1.50"
serde = { version = "1.0", features = ["derive"] }
>>>>>>> origin/runner-implementation:riklet/src/crates/oci/Cargo.toml
