[package]
name = "daemon"
version = "0.1.0"
authors = ["Hugo Amalric <hugoamalric@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# client binary
[[bin]]
name = "client"
path = "riklet.rs"