[package]
name = "oci"
version = "0.1.0"
authors = ["Thomas Gouveia <thomas.gouveia@ioterop.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
command = { path = "../command" }
log = "0.4.14"
